name: devt12
version: git
summary: Command line weather tool.
description: |
  Get current weather:-
    $ wethr
  Get current weather in metric units
    $ wethr --metric
  Get current weather in imperial units
    $ wethr --imperial

base: core18
confinement: devmode

parts:
  test-wethr:
    plugin: nodejs
    source: .
    nodejs-version: '10.19.0'
    nodejs-package-manager: 'npm'

apps:
  devt12:
    command: wethr
architectures:
  - build-on: [armhf,amd64]
    run-on: [armhf,amd64]
